"""
PrivaVault — Encryption Service
Phase 6-7 | branch: feature/encryption-download

Responsibilities:
  - Encrypt raw file bytes with a fresh Fernet key per file
  - Derive a wrapping key from password + PBKDF2 salt using PBKDF2-HMAC-SHA256
  - Wrap the Fernet key with the derived wrapping key
  - Unwrap the Fernet key later during download
  - Wipe sensitive key material from RAM as much as Python allows

Important implementation notes:
  - The Fernet key is unique per file.
  - The wrapping key is derived from the user's password and stored PBKDF2 salt.
  - The wrapping key never leaves RAM.
  - The wrapped Fernet key is what gets persisted in documents.encrypted_key_blob.
"""

import base64
from typing import Tuple

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC


PBKDF2_ITERATIONS = 600_000
PBKDF2_KEY_LENGTH = 32


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------
def _normalize_salt(pbkdf2_salt: str | bytes) -> bytes:
    if isinstance(pbkdf2_salt, bytes):
        return pbkdf2_salt

    # pbkdf2_salt is always generated by secrets.token_hex(32) in auth.py
    # so it is always valid hex — no fallback needed.
    # If this raises ValueError, something is genuinely wrong upstream.
    return bytes.fromhex(pbkdf2_salt.strip())


def _derive_wrapping_key(password: str, pbkdf2_salt: str | bytes) -> bytearray:
    """
    Derive a Fernet-compatible wrapping key from the user's password.
    Returns mutable bytearray so caller can zero it after use.
    """
    salt_bytes = _normalize_salt(pbkdf2_salt)
    password_bytes = password.encode("utf-8")

    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=PBKDF2_KEY_LENGTH,
        salt=salt_bytes,
        iterations=PBKDF2_ITERATIONS,
    )
    raw_key = kdf.derive(password_bytes)
    wrapping_key = bytearray(base64.urlsafe_b64encode(raw_key))

    del password_bytes, raw_key, salt_bytes
    return wrapping_key


def _fernet_from_key(key_material: bytes | bytearray) -> Fernet:
    """Build a Fernet instance from urlsafe-base64 key material."""
    return Fernet(bytes(key_material))


def _wipe_bytearray(buffer: bytearray | None) -> None:
    """Overwrite a mutable buffer in place before dropping the reference."""
    if buffer is None:
        return
    for index in range(len(buffer)):
        buffer[index] = 0


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def encrypt_file(file_bytes: bytes, password: str, pbkdf2_salt: str | bytes) -> Tuple[bytes, bytes]:
    """
    Encrypt raw file bytes and wrap the file key.

    Args:
        file_bytes: Raw file bytes to encrypt.
        password: User's raw password from the active request.
        pbkdf2_salt: User's stored PBKDF2 salt from the users table.

    Returns:
        (ciphertext, encrypted_key_blob)
        ciphertext         → goes to Azure Blob Storage
        encrypted_key_blob → goes to documents.encrypted_key_blob in MySQL
    """
    fernet_key = bytearray(Fernet.generate_key())
    wrapping_key = None

    try:
        file_fernet = _fernet_from_key(fernet_key)
        ciphertext = file_fernet.encrypt(file_bytes)

        wrapping_key = _derive_wrapping_key(password, pbkdf2_salt)
        key_wrapper = _fernet_from_key(wrapping_key)
        encrypted_key_blob = key_wrapper.encrypt(bytes(fernet_key))

        return ciphertext, encrypted_key_blob
    finally:
        _wipe_bytearray(fernet_key)
        _wipe_bytearray(wrapping_key)
        del fernet_key, wrapping_key


def unwrap_file_key(encrypted_key_blob: bytes, password: str, pbkdf2_salt: str | bytes) -> bytes:
    """
    Unwrap the Fernet key used to encrypt a file.

    Args:
        encrypted_key_blob: Wrapped Fernet key from documents.encrypted_key_blob.
        password: User's raw password from the active request.
        pbkdf2_salt: User's stored PBKDF2 salt from the users table.

    Returns:
        bytes: The unwrapped Fernet key — pass this into Fernet(...) to decrypt
               the ciphertext fetched from Azure Blob Storage.

    Note:
        This function does NOT decrypt the file itself.
        The caller fetches the ciphertext from Blob Storage and
        decrypts it using the returned key.
    """
    wrapping_key = None

    try:
        wrapping_key = _derive_wrapping_key(password, pbkdf2_salt)
        key_unwrapper = _fernet_from_key(wrapping_key)
        fernet_key = key_unwrapper.decrypt(encrypted_key_blob)
        return fernet_key
    finally:
        _wipe_bytearray(wrapping_key)
        del wrapping_key